### ISSUE TITLE
is this commend right?

### ISSUE THREAD

**Issue by 5thgfka** [titu1994/Neural-Style-Transfer#1]
python Network.py '/home/ekse/Pictures/QQphoto.jpeg' '/home/ekse/Pictures/starry_night.jpg' '' --image_size 400 --content_weight 0.025 --style_weight 1 --total_variation_weight 1E-05 --style_scale 1 --num_iter 1 --rescale_image "False" --rescale_method "billinear" --maintain_aspect_ratio "True" --content_layer "conv5_2" --init_image "content" --pool_type "ave"

but it took me half hour and no result.

thank you.

**Comment by 5thgfka** [comment]
I ran it on a x64 CentOS virtual machine with 2 core cpu, 2G RAM. 
i3-4130 CPU 3.40GHz

**Comment by 5thgfka** [comment]
without GPU

**Comment by titu1994** [comment]
I've only tested this on Windows but it should work nevertheless. Each epoch requires 11 seconds on a 980 M gpu. Perhaps working on CPU in a virtual environment is slowing it down drastically.  

As to the parameters, it is correct. As a suggestion (which may not make any difference), try supplying the the paths in double quotes and also supply the prefix.

**Comment by 5thgfka** [comment]
@titu1994 
Thank you. It works, but after Start of iteration, when doing fmin_l_bfgs_b, it slows down. I wait. : )

**Comment by titu1994** [comment]
Yes. GPU is very much recommended for this since it uses the VGG network.
