### ISSUE TITLE
Probably simple error

### ISSUE THREAD

**Issue by shenkev** [titu1994/Neural-Style-Transfer#15]
Hi there,

Sorry this may be very obvious but as a new user of Theano I haven't seen this error before. I appreciate your help.

Command:
python Network.py "/images/inputs/content/golden_gate.jpg" "/images/inputs/style/picasso_selfport1907.jpg" "/myouts/output"

Error:
Using Theano backend.
Traceback (most recent call last):
  File "Network.py", line 109, in <module>
    if len(style_image_paths) != len(args.style_weight):
TypeError: object of type 'int' has no len()

**Comment by titu1994** [comment]
@shenkev Sorry for that. It's a bug that occurs when you use the script without the Script Helper program. I generally run the scripts via the helper so I never encountered this bug.

I've pushed a commit which should fix this bug right now. However, I suggest that if you have Mono installed, use the Script Helper. It provides far more flexibility in manipulating the script and warns you if there is some mistake. 

It's available in the Releases tab of the project : https://github.com/titu1994/Neural-Style-Transfer/releases
