### ISSUE TITLE
environment.yml

### ISSUE THREAD

**Issue by lettergram** [titu1994/Neural-Style-Transfer#2]
I recommend adding an environment.yml file so conda can easily be used to install everything.

**Comment by titu1994** [comment]
@lettergram While I would like to do that, I didn't create an environment in conda specifically for this project so creating an environment.yml file will be slightly difficult. 

In any case, most of the requirements are installed directly when installing Anaconda of any version. The only notable exception is Keras itself, which can always be downloaded via pip.
