### ISSUE TITLE
Selecting Anaconda python.exe in Linux

### ISSUE THREAD

**Issue by crypdick** [titu1994/Neural-Style-Transfer#30]
When I am running the script GUI with Ubuntu+Mono and I hit `Compute`, it prompts me for the Anaconda python as expected. However, it only accepts  'python.exe'. I switch the dropdown to `All Files` and select `/path/to/anaconda2/bin/python2.7`. It didn't work though, and it renders the `Compute` button useless :\

So was I supposed to download Anaconda for Windows and save it alongside my Linux Anaconda?

**Comment by titu1994** [comment]
Not at all. Are you using a recent version of the script helper ? 

I put an update in there to search for both python.exe and just python so that it would work in Linux as well with Mono. 

Could you try the latest release from the release tab?

**Comment by crypdick** [comment]
I followed your directions but I think I found the error. I ran the script from Mono in terminal and got this:

```
Could not set X locale modifiers
"/home/richard/Apps/Neural-Style-Transfer/images/inputs/content/tubingen.jpg" "/home/richard/Apps/Neural-Style-Transfer/images/inputs/style/candy-style.jpg" "/home/richard/Apps/Neural-Style-Transfer/script_helper/test.jpg" --image_size 400 --content_weight 0.025 --style_weight 1.0 --total_variation_weight 8.5E-05 --style_scale 1 --num_iter 10 --rescale_image "False" --rescale_method "bicubic" --maintain_aspect_ratio "True" --content_layer "conv5_2" --init_image "content" --pool_type "max" --preserve_color "False" --min_improvement 0 --model "vgg16" --content_loss_type 0
/home/richard/Apps/anaconda2/bin/python2.7: can't open file 'Script/INetwork.py': [Errno 2] No such file or directory
```

It looks like maybe it's due to an issue with relative directories?

**Comment by titu1994** [comment]
The program should have a scripts directory with 4-5 python scripts. 

Clicking on the compute button should start start the python exe at the location of the program, which then uses relative path to get to Scripts folder and then execute the appropriate script. 

I haven't tested this with Linux much. Doesn't the executable .exe launch python at the path that the program is ? 

I'll see if I can make the path absolute from current working directory in some time.
