### ISSUE TITLE
"IndexError: tuple index out of range"

### ISSUE THREAD

**Issue by canadaduane** [titu1994/Neural-Style-Transfer#33]
I'm running the sample images (using either the theano or tensorflow backends) and get the following error: `IndexError: tuple index out of range`

```
~/arts/Neural-Style-Transfer$ python Network.py images/inputs/content/Japanese-cherry-widescreen-wallpaper-Picture-1366x768.jpg images/inputs/style/candy-style.jpg images/inputs/style/water-lilies-1919-2.jpg "Cherry Blossom" --style_masks images/inputs/mask/cherry-blossom-1.jpg images/inputs/mask/cherry-blossom-2.jpg --content_weight 5 --style_weight 1.0 1.0 --num_iter 20 --model vgg16 --content_loss_type 0
Using TensorFlow backend.
Traceback (most recent call last):
  File "Network.py", line 319, in <module>
    x = Convolution2D(64, (3, 3), activation='relu', name='conv1_1', padding='same')(ip)
  File "/home/artcade/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 615, in __call__
    output_shape = self.compute_output_shape(input_shape)
  File "/home/artcade/anaconda2/lib/python2.7/site-packages/keras/layers/convolutional.py", line 193, in compute_output_shape
    self.kernel_size[i],
IndexError: tuple index out of range
```

I've installed the following versions of CUDA and cuDNN:

```
cuda_8.0.61_375.26_linux.run
cudnn-8.0-linux-x64-v6.0.tgz
```

I'm running this on Linux, on an NVidia 1080 GPU.

I suspect I'm doing something simple but wrong. Any idea where to look?

**Comment by titu1994** [comment]
Try putting all paths in double quotes.

**Comment by canadaduane** [comment]
I tried with several sets of files, including some that have no spaces or
other difficult characters for the shell. I can try quotes. It would
surprise me if this is the solution.

I investigated the index error and found that the "space" tuple has the
form `(None, 5, 500, 300, 4)` or thereabouts. The library tries to slice
the space tuple to get the kernel tuple, but gets the None and fails when
the space and kernel tuples' sizes don't match.

I don't understand the library well enough at a high level to see what may
be causing this. Does that help identify an underlying issue, perhaps?

**Comment by titu1994** [comment]
Did you try using double quotes ? My program has that same problem, so I had to endorse quotes to get it to work.

**Comment by canadaduane** [comment]
I will try as soon as I'm back at the lab :)

**Comment by canadaduane** [comment]
Adding double quotes did not solve this issue. It appears to be a possible incompatibility introduced during the switch to keras 2. Reverting to 1.2.2 and using an HEAD^ fixed the issue for us.

**Comment by titu1994** [comment]
Hmm that is weird. I have run this program in Keras 2 for around 1 month now, with no issue. 

Could you try using the Windows Helper script ? I test using that, since it format the arguments properly.

**Comment by canadaduane** [comment]
We're running on Linux... Does that Windows script work there also?

**Comment by titu1994** [comment]
Yes, it works with Mono installed. There's no need to make any changes other than install `mono-complete`.
