### ISSUE TITLE
Multi scale transfer

### ISSUE THREAD

**Issue by rachelebellini** [titu1994/Neural-Style-Transfer#42]
Hello,

I am interested in the multi-scale transfer you showed. I couldn't however understand the process very well. Could you list the steps you did? especially, how do you combine the different scales (192x192, 384x384, 768x768)?

Thank you!

**Comment by titu1994** [comment]
Its not a combination usage. Its stepwise.

1) Load initial content image (C), style image. Set image size to 128. Run algo for 50-100 iterations. Save result as R1.
2) Change image size to twice previous layer.
3) Set "Initial Layer" as "<Choose Image>". In popup choose previous result image (R1, R2, ..., Ri). 
4) Run algo 50-100 iterations. Save result as Ri+1 (2nd image scale = R2, 3rd image scale = R3)
5) Repeat 2 onwards.
