### ISSUE TITLE
about Neural Style Transfer.exe

### ISSUE THREAD

**Issue by BeibiKissU** [titu1994/Neural-Style-Transfer#43]
I read the reference. and it said i should download mono C# to use Neural Style Transfer.exe. After all the requirements i installed, i still can not run “Neural Style Transfer.exe”. Besides, i used linux and keras theano bankend .  So my question is how to run “Neural Style Transfer.exe”, how to open it?  I tried to just click it, or 'mono “Neural Style Transfer.exe”'. It did not use.
thanks

**Comment by titu1994** [comment]
Sorry for the delay. The error is on Mono is now fixed via : https://github.com/titu1994/Neural-Style-Transfer/releases/tag/v0.2.7.3
