### ISSUE TITLE
multiple style transfer

### ISSUE THREAD

**Issue by ivanpang1996** [titu1994/Neural-Style-Transfer#44]
After read #21 , I have a question about the masked style transfer.
If Mask A has combined with style A and so on for Mask B, then how to combine both images as a output?

Thanks and best regards

**Comment by titu1994** [comment]
That comment kinda explains it properly, so I won't reiterate that. Simply put, you can think of a 1:1 map from a binary mask to a single style. You can split the images into sections of white or black, and choose the corresponding style to affect the white masked region.
