### ISSUE TITLE
Issue with Running on Colab

### ISSUE THREAD

**Issue by 123srb** [titu1994/Neural-Style-Transfer#47]
When running the application through the Collab link I'm getting this error on line 35:

/bin/sh: 1: Syntax error: "(" unexpected

!python {dir_path}/{NETWORK} {CONTENT_IMAGE_FN} {STYLE_IMAGE_FN} {RESULT_PREFIX} \
  --image_size {IMAGE_SIZE} --content_weight {CONTENT_WEIGHT} --style_weight \
  {STYLE_WEIGHT} --style_scale {STYLE_SCALE} --total_variation_weight \
  {TOTAL_VARIATION_WEIGHT} --content_loss_type {CONTENT_LOSS_TYPE} --num_iter \
  {NUM_ITERATIONS} --model {MODEL} --rescale_image {RESCALE_IMAGE} \
  --maintain_aspect_ratio {MAINTAIN_ASPECT_RATIO} --content_layer {CONTENT_LAYER} \
  --init_image {INITIALIZATION_IMAGE} --pool_type {POOLING_TYPE} --preserve_color \
  {PRESERVE_COLOR} --min_improvement {MIN_IMPROVEMENT}

**Comment by titu1994** [comment]
I don't add brackets anywhere and I have used this script often these days. Perhaps one of the variables that it requires has a bracket ? Check the values of all the variables that this script calls. 

Or perhaps it's an issue with the name of the source or content image? If it has brackets that can cause this issue.

**Comment by 123srb** [comment]
Yes, you're right! One of the files had ( in it.  Thank you, issue solved!
