### ISSUE TITLE
Not able to reproduce the results

### ISSUE THREAD

**Issue by tj198505** [titu1994/Neural-Style-Transfer#50]
Hi, 

With all default settings in the jupyter notebook, the generated results does not look any similar to the results you posted. 
I did not use google.colab to import content and style images, instead, the image are directly set by 
CONTENT_IMAGE_FN = "../deepArt.ai/test/blue-moon-lake.jpg"
STYLE_IMAGE_FN = "../deepArt.ai/test/starry_night.jpg"

![gen_at_iteration_10](https://user-images.githubusercontent.com/44076626/46845619-acf49280-ce38-11e8-8284-855ec590255b.png)

**Comment by titu1994** [comment]
You need to run it for 100 epochs. It's quite slow so I set the default as 10 epochs.

**Comment by tj198505** [comment]
Here is the result with 100 epochs
![gen_at_iteration_100](https://user-images.githubusercontent.com/44076626/47044133-e425c380-d1eb-11e8-9673-0e05652ca0e9.png)

**Comment by titu1994** [comment]
Hmm interesting. I can't recall the set of combinations that I ran to get the result, but it definitely wasn't the default settings I've posted here. I do remember epochs being 100, and changing a few other parameters.

The defaults are good baselines, but each image generally needs specific settings of parameters to get great results.

**Comment by tj198505** [comment]
Which parameters you have change to achieve better results? What is your strategy to change them?

**Comment by titu1994** [comment]
Well, I used Inetwork, and used more style weights. It's a trial and error process, and that's from nearly two years ago so I don't remember.

**Comment by tj198505** [comment]
Should this issue be 'open' then? Someone else may have the same issue.

**Comment by titu1994** [comment]
You could in essence try variations of the settings on Colab and see which setting gets you the result. 

This issue is closed because it is very challenging to get the exact setting which gets the best output. Sadly, I have a folder of over 300+ images which were failed attempts of just 1 single image.
