### ISSUE TITLE
Trying to under stand the loss functions

### ISSUE THREAD

**Issue by csinpi** [titu1994/Neural-Style-Transfer#53]
https://github.com/titu1994/Neural-Style-Transfer/blob/536a96df79dc6c155eb84ded3bd71cdd21553d1e/INetwork.py#L513

Between these two lines, sl is only decided by the last style image? Am I understanding it correctly?

**Comment by titu1994** [comment]
J is indexing each of the available style layers. Sl1 and Sl2 compute the loss separately for each of the J style images passed, and then sl computes the difference between each of these (sl1_j, sl2_j) pairs, and these differences are summed up using geometric weighing of the loss terms based on depth of the network.

**Comment by csinpi** [comment]
That makes sense. For some reason I thought Line 518 was outside the for-loop started in Line 513. Thanks for the prompt reply.

**Comment by titu1994** [comment]
Glad I could help!
