### ISSUE TITLE
Easy Linux Install

### ISSUE THREAD

**Issue by minihat** [titu1994/Neural-Style-Transfer#54]
This project is, by far, the easiest to set up of the nn style transfer repos I've encountered. It might be nice to include in the guide a brief example of a conda environment setup that works on Ubuntu (with anaconda):

`conda create -n nst numpy scipy pil h5py keras tensorflow-gpu`

As long as you have an NVIDIA GPU and latest driver installed ahead of time, this will relieve you of the need to manually install CUDA and cuDNN.

**Comment by titu1994** [comment]
Seems like a good idea. If you'd like credit, it would be great if you add a PR to update the readme or the guide.md.
