### ISSUE TITLE
ImportError: cannot import name 'imread'

### ISSUE THREAD

**Issue by Ruqyai** [titu1994/Neural-Style-Transfer#64]
Traceback (most recent call last):
  File "Neural-Style-Transfer/color_transfer.py", line 9, in <module>
    from scipy.misc import imread, imresize, imsave, fromimage, toimage
ImportError: cannot import name 'imread'

**Comment by elctrc** [comment]
@Ruqyai you, like me, likely installed the most recent version of SciPy, which no longer contains the imread method. See here: https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.imread.html

I have tried using imageio - you need to also update line 116 and change the parameter "mode" to "pilmode". But tbh even after doing that I am just getting different errors:

`Traceback (most recent call last):
  File "color_transfer.py", line 116, in <module>
    generated_image = imread(args.generated_image, pilmode="RGB")
  File "/home/kidd/anaconda3/envs/nst/lib/python3.7/site-packages/imageio/core/functions.py", line 264, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/home/kidd/anaconda3/envs/nst/lib/python3.7/site-packages/imageio/core/functions.py", line 182, in get_reader
    "Could not find a format to read the specified file " "in mode %r" % mode
ValueError: Could not find a format to read the specified file in mode 'i'`

**Comment by darshana1406** [comment]
In the color_transfer.py file add this:
`from utils import imread, imresize, imsave, fromimage, toimage`
and remove this:
`from scipy.misc import imread, imresize, imsave, fromimage, toimage`

**Comment by dkarma** [comment]
it's really sad that great projects like these get utterly destroyed by changes in the underlying libraries.  basically this entire neural doodle tree is completely broken by depricated functions in scipy and other libraries.

imo devs have an obligation to tell people their stuff is broken (and pull it from github) if the underlying dependencies break.  
this all needs to be rewritten and does not work as-is

**Comment by titu1994** [comment]
1- don't repeat your comment as a seperate issue (or instead don't paste your issue in other issues)

2-
I (or any other dev) have absolutely 0 obligation to do anything at all if the underlying libraries change and break an application. If I volunteer to maintain it then thats volunteering, not an obligation on my part.

Nothing stops you from volunteering some of your own time maintaining the project and sending PR to update it, so feel free to do that if you feel so strongly about it.

**Comment by Ruqyai** [comment]
.
