### ISSUE TITLE
could we apply fast-style-transfer to image deformation?

### ISSUE THREAD

**Issue by erhuodaosi** [titu1994/Neural-Style-Transfer#67]
I'm sorry to bother you,but I have a question on could we apply Neural-Style-Transfer to image deformation.

In style-transfer,we usually provide a content image and a style image to generate results.And now,could we give a content picture,and let it transform into a warpping image?If the answer is yes,what is the style image?How could we get the style image?

Here are two pictures:one is the original picture,and the other is the transformed image.
![before](https://user-images.githubusercontent.com/45588148/87241475-1bbfaf00-c456-11ea-86ba-2202ae624a37.png)
![after](https://user-images.githubusercontent.com/45588148/87241476-20846300-c456-11ea-885c-15ab6e76e569.png)

I would very appreciate if you could help me,thank you!

**Comment by titu1994** [comment]
This sounds like perspective warping of images, which has several classic methods implemented in the cv2 library.

**Comment by erhuodaosi** [comment]
@titu1994 Thank you very much.I have tested using CV2 method ,but the result is not very good.
