### ISSUE TITLE
broken and unusable

### ISSUE THREAD

**Issue by dkarma** [titu1994/Neural-Style-Transfer#81]
it's really sad that great projects like these get utterly destroyed by changes in the underlying libraries.  basically this entire neural doodle tree is completely broken by depricated functions in scipy and other libraries.

imo devs have an obligation to tell people their stuff is broken (and pull it from github) if the underlying dependencies break.  
this all needs to be rewritten and does not work as-is

**Comment by titu1994** [comment]
I (or any other dev) have absolutely 0 obligation to do anything at all if the underlying libraries change and break an application. If I volunteer to maintain it then thats volunteering, not an obligation on my part. 

Nothing stops you from volunteering some of your own time maintaining the project and sending PR to update it, so feel free to do that if you feel so strongly about it.
