### ISSUE TITLE
Windows Helper Programm

### ISSUE THREAD

**Issue by supertobi** [titu1994/Neural-Style-Transfer#9]
Where can I find the code of the windows helper program?

**Comment by titu1994** [comment]
@supertobi The code is available at : https://github.com/titu1994/Neural-Style-Transfer-Windows

It's not very polished though. Simple wrapper over the python script with some validation. I still have to validate the variables for neural doodle scripts.

Edit: It's a Visual Studio 2015 project.

**Comment by supertobi** [comment]
Thanks for the fast information.
